#cloud-config
autoinstall:
  version: 1

  storage:
    layout:
      name: lvm

  packages:
    - vim
    - chromium
    - simple-scan
    - cheese
    - vlc
    - libreoffice
    - flatpak
    -gnome-software-plugin-flatpak

  late-commands:
    - curtin in-target -- flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
